Vagrant.configure("2") do |config|
  config.vm.box = "google/gce"

  config.vm.provider :google do |google, override|
    google.google_project_id = "vibratoproject-180500"
    google.google_client_email = "jralmaraz1@gmail.com"
    google.google_json_key_location = "/home/jralmaraz/Documents/2017/GoogleCloud/api-credentials/VibratoProject-24b0d64ebd63.json"
    google.image = "ubuntu-1604-xenial-v20170815a"
#    google.external_ip = "35.192.3.7"
    override.ssh.username = "jralmaraz"
    google.metadata = {'key' => 'startup-script' , 'value' => 'apt-get update\napt-get install -y apache2' }
    #override.ssh.private_key_path = "~/.ssh/id_rsa"
    override.ssh.private_key_path = "~/.ssh/google_compute_engine"
  end

end
