Vagrant.configure("2") do |config|
  config.vm.box = "google/gce"

  config.vm.provider :google do |google, override|
    google.google_project_id = "vibratoproject-180500"
    google.google_client_email = "jralmaraz1@gmail.com"
    google.google_json_key_location = "/home/jralmaraz/Documents/2017/GoogleCloud/api-credentials/VibratoProject-24b0d64ebd63.json"

    google.zone = "australia-southeast1-a"

    google.zone_config "australia-southeast1-a" do |zone1a|
        zone1a.name = "vibrato-test"
        zone1a.image = "ubuntu-1604-xenial-v20170815a"
        zone1a.machine_type = "n1-standard-4"
        zone1a.zone = "australia-southeast1-a"
        zone1a.metadata = {'instances' => 'metadata', 'startup-script' => '#! /bin/bash 
									    apt-get update 
									    apt-get install -y apache2
									    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
									    apt-add-repository ppa:ansible/ansible

									    apt-get install -y software-properties-common

									    sleep 5

									    apt-get update

									    sleep 5

									    apt-get install -y ansible
									    
									    sudo git clone https://github.com/jralmaraz/vibrato-tech-task /var/www/html/vibrato-tech-task
									    
									    mv /var/www/html/vibrato-tech-task/vagrant/vibrato-playbook.yml /home/vagrant/  
									    
									    ansible-playbook /home/vagrant/vibrato-playbook.yml

									    mv /var/www/html/vibrato-tech-task/sample-codes/*.php /var/www/html/

									    mv /var/www/html/vibrato-tech-task/sample-codes/*.sql /home/vagrant/

									    mysql test < /home/vagrant/sample-data.sql

									    IP="$(curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/ip)"

									    echo "To access the applications, use the following URLs (PLEASE NOTE THAT THE RETRIEVED IP ADDRESS NEEDS PUBLIC ACCESS):

									      Insert new record: http://$IP/insert.php
									      Retrieve records: http://$IP/users.php"'}
        zone1a.scopes = ['bigquery', 'monitoring', 'https://www.googleapis.com/auth/compute']
        zone1a.tags = ['web', 'app']
    end
    
    override.ssh.username = "jralmaraz"
    google.metadata = {'key' => 'startup-script' , 'value' => 'apt-get update\napt-get install -y apache2' }
    #override.ssh.private_key_path = "~/.ssh/id_rsa"
    override.ssh.private_key_path = "~/.ssh/google_compute_engine"
  end
  #config.vm.provision :shell, path: "bootstrap.sh"
end
