Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "VibratoTechTask"
  config.vm.network "public_network", ip: "192.168.1.17", bridge: "wlan0"
  config.vm.provision "file", source: "~/Documents/2017/Vagrant/ubuntu/vibrato-playbook.yml", destination: "/home/vagrant/vibrato-playbook.yml"
  config.vm.provision :shell, path: "bootstrap.sh"
  #
  # Run Ansible from the Vagrant Host
  #
  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "vibrato-playbook.yml"
  #end
end

